sudo: required
addons:
  firefox: latest-esr
      
language: node_js
node_js:
  - 10


services:
  - xvfb

before_script:
# - sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
  - cd ./server 
  - npm install -g ionic cordova
  - npm install
  
  

script:
  - npm test