sudo: required
addons:
  firefox: latest-esr
      
language: node_js
node_js:
  - 10


services:
  - xvfb

before_script:
# - sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
  - cd ./server 
  - npm install -g ionic cordova
  - npm install
  
jobs:
  include:
    - stage: Unit-Testing
      name: Server-Side-Unit-Test
      language: node_js
      script: npm run unit
    - stage: Integration-Testing
      name: Server-Side-Integration-Test
      language: node_js
      script: npm run integration